[package]
name = "kmerutils"
version = "0.0.1"
authors = ["jeanpierre.both@gmail.com"]
edition = "2018"


[features]

# declare a feature with no dependancy to get some modulated debug print
# to be run with cargo build --features verbose_1
#verbose_1 = [ ]

[[bin]]

name= "parsefastq"
path= "src/bin/parsefastq.rs"

[[bin]]

name= "qualityloader"
path= "src/bin/qualityload.rs"

[[examples]]

name="kmerreload"
path="examples/reloadkmermulti.rs"


[lib]

lib = "kmerutils"
path = "src/lib.rs"
test=true

doc=true
#[[example]]




[dependencies]
# default is version spec is ^ meaning can update up to max non null version number
# cargo doc --no-deps avoid dependencies doc generation
#

serde= {version = "1.0", doc = false}
serde_derive={ version = "1.0", doc = false}

histogram =  {version = "0.6", doc = false}

multimap= {version =  "0.4.0", doc = false}

# for networking
zmq= {version =  "0.8.2"}
xdr-codec= {version = "0.2.5" , doc = false}

# for //
crossbeam-utils = "0.7"
crossbeam-channel = "0.2"

parking_lot = "0.11"
rayon = {version = "1.4",  doc = false}
num_cpus = {version = "1.13.0", doc = false}

time = {version = "0.2",  doc = false}
ndarray = {version = "0.13" , doc = false}
needletail = "0.4.0"
wavelet-matrix = { version = "0.4.7", doc = false}
clap = {version = "2.33", doc = false}

#  for hashing 
rand = {version = "0.7", doc = false}
rand_xorshift = {version = "0.2", doc = false}

cuckoofilter = {version="0.5", doc=false}
bloom = {version="0.3", doc=false}
metrohash = "1.0.5"

fxhash = { version= "0.2"}
fnv = {version= "1.0"}

lazy_static = { version = "1.4"}

redis = { version = "0.9.0"}
# decreasing order of log for debug build : (max_level_)trace debug info warn error off
# decreasing order of log for release build (release_max_level_)  .. idem
log = { version = "0.4", features = ["max_level_debug", "release_max_level_debug"] }
simple_logger = { version = "1.0"}
